import assert from 'node:assert/strict';
import {suite,test,summary} from './harness.js';
import {cents,validDate,validateDocument} from '../specialists/accountant-cz/workflow/common.js';
import {computeMonthly} from '../specialists/accountant-cz/workflow/monthly.js';
import {computeAnnual,spouseEligibleMonths,ANNUAL_FACTS,socialAdvance2026} from '../specialists/accountant-cz/workflow/annual.js';
import {deadlines,businessDate,calendar} from '../specialists/accountant-cz/workflow/deadlines.js';
import {monthlyForms,annualForms,ozpPDFFields} from '../specialists/accountant-cz/workflow/forms.js';
import {extractDocument} from '../specialists/accountant-cz/workflow/extraction.js';

const months=Array.from({length:12},(_,i)=>i+1);
function fixture(kind='annual'){
  const p={firstName:'Test',lastName:'Příklad',dic:'7001010007',birthNumber:'7001010007',taxOffice:'451',taxOfficeBranch:'2001',street:'Testovací',houseNumber:'1',city:'Praha',postalCode:'11000',confirmed:true,vatPayer:true,nace:'620100',csszOffice:'101',socialVariableSymbol:'12345678',healthInsurer:'207'};
  const answers={};for(const[k,,t]of ANNUAL_FACTS)answers[k]=t==='boolean'?false:t==='money'?0:null;
  Object.assign(answers,{cashBasis:true,mainActivityAllYear:true,sameInsurerAllYear:true,sameMainActivity2026:true,czechTaxResident:true,onlyDomesticSelfEmployment:true,incomeComplete:true,boundaryInvoices:true,expenseRate:60,children:[],filingMode:'basic',domesticStandardOnly:true,monthComplete:true,taxAdvancesEvidence:'support',socialAdvancesEvidence:'support',healthAdvancesEvidence:'support'});
  return {id:'test-case',kind,year:kind==='annual'?2025:2026,month:5,revision:1,profile:p,answers,sources:[{id:'source'}],documents:[{id:'support',sourceId:'source',kind:'support',status:'approved',label:'Syntetické potvrzení'}]};
}
function invoice({id='invoice',base=1000000,rate=21,date='2025-01-05',paid='2025-01-10',direction='income'}={}){
  const vat=Math.round(base*rate/100),total=base+vat;return {id,kind:'invoice',status:'approved',sourceId:'source',label:id,fields:{number:id,date,vatDate:date,receivedDate:date,totalCents:total,rows:[{rate,baseCents:base,vatCents:vat}],currency:'CZK',supplierDic:direction==='income'?'CZ7001010007':'CZ12345679',customerDic:direction==='income'?'CZ12345679':'CZ7001010007',direction,customerVatPayer:true,claimVat:true,paymentStatus:'paid',payments:[{date:paid,amountCents:total,evidenceId:'support'}]}};
}
suite('Accountant operator workflow — statutory boundaries');
test('CZK is parsed as exact integer halere, invalid dates/precision rejected',()=>{assert.equal(cents('1 234,56'),123456);assert.throws(()=>cents('12,345'));assert.equal(validDate('2025-02-29'),false);});
test('full annual evidence is ready, missing source is a named request',()=>{const c=fixture();c.documents.push(invoice());assert.equal(computeAnnual(c).status,'READY_FOR_EXPORT');delete c.answers.socialAdvancesEvidence;assert(computeAnnual(c).questions.some(q=>q.key==='socialAdvancesEvidence'));});
test('December invoice paid in January counts in payment year, January due date is not a payment',()=>{const c=fixture();c.documents.push(invoice({date:'2024-12-20',paid:'2025-01-03'}),invoice({id:'next',date:'2025-12-20',paid:'2026-01-03'}));assert.equal(computeAnnual(c).income,10000);c.documents[1].fields.paymentStatus='unknown';assert(computeAnnual(c).questions.some(q=>q.type==='payment'));});
test('partial receipts across years allocate net exactly and require evidence',()=>{const c=fixture(),d=invoice({base:10001});d.fields.payments=[{date:'2024-12-31',amountCents:5000,evidenceId:'support'},{date:'2025-01-02',amountCents:d.fields.totalCents-5000,evidenceId:'support'}];c.documents.push(d);assert.equal(computeAnnual(c).receivedIncomeCents,5869);assert.equal(computeAnnual(c).income,58.69);d.fields.payments[1].evidenceId='absent';assert(computeAnnual(c).questions.some(q=>q.type==='payment'));});
test('expense cap and annual golden arithmetic match a synthetic hand-calculated fixture',()=>{const c=fixture();c.documents.push(invoice({base:220000000}));Object.assign(c.answers,{claimSpouse:true,spouse:{firstName:'Test',lastName:'Manželka',birthNumber:'9051010002',marriedSince:'2020-01-01',householdMonths:months,annualIncomeCents:0,ztpP:false},spouseEvidence:'support',childrenEvidence:'support',socialAdvances:9829200,children:[{firstName:'Dítě',lastName:'První',birthNumber:'2106010000',birthDate:'2021-06-01',householdMonths:months,ztpP:false,claims:months.map(month=>({month,order:1}))},{firstName:'Dítě',lastName:'Druhé',birthNumber:'2306010000',birthDate:'2023-06-01',householdMonths:months,ztpP:false,claims:months.map(month=>({month,order:2}))}]});const r=computeAnnual(c);assert.equal(r.status,'READY_FOR_EXPORT');assert.equal(r.expenses,1200000);assert.equal(r.base,1000000);assert.equal(r.rawTax,150000);assert.equal(r.tax,56796);assert.equal(r.social,160600);assert.equal(r.socialBalance,62308);assert.equal(r.newSocial,13384);});
test('spouse limit is whole year, newborn eligibility starts next month, third birthday on 1st excludes that month',()=>{const a={spouse:{marriedSince:'2020-01-01',householdMonths:months,annualIncomeCents:6800000},children:[{birthDate:'2025-03-15',householdMonths:months}]};assert.deepEqual(spouseEligibleMonths(a,2025),[4,5,6,7,8,9,10,11,12]);a.spouse.annualIncomeCents++;assert.deepEqual(spouseEligibleMonths(a,2025),[]);a.spouse.annualIncomeCents=0;a.children[0].birthDate='2022-06-01';assert.deepEqual(spouseEligibleMonths(a,2025),[1,2,3,4,5]);});
test('spouse eligible credit needs signed material, declaring low income is insufficient',()=>{const c=fixture();Object.assign(c.answers,{claimSpouse:true,spouse:{firstName:'A',lastName:'B',birthNumber:'9051010002',marriedSince:'2020-01-01',householdMonths:months,annualIncomeCents:0,ztpP:false},children:[{firstName:'A',lastName:'B',birthNumber:'2306010000',birthDate:'2023-06-01',householdMonths:months,claims:[],ztpP:false}]});assert(computeAnnual(c).questions.some(q=>q.key==='spouseEvidence'));});
test('pension/life/DIP/care share 48000 cap and require issuer evidence',()=>{const c=fixture();c.documents.push(invoice({base:500000000}));for(const key of ['pension','lifeInsurance','dip','longTermCare'])Object.assign(c.answers,{[key]:true,[key+'Amount']:2000000,[key+'Eligible']:true,[key+'Evidence']:'support'});assert.equal(computeAnnual(c).deductions,48000);delete c.answers.lifeInsuranceEvidence;assert(computeAnnual(c).questions.some(q=>q.key==='lifeInsuranceEvidence'));});
test('child bonus income floor, duplicate child-month/order, unsupported year fail closed',()=>{const c=fixture();c.documents.push(invoice({base:1000000}));c.answers.children=[{firstName:'A',lastName:'B',birthNumber:'2306010000',birthDate:'2023-06-01',householdMonths:months,ztpP:false,claims:months.map(month=>({month,order:1}))}];assert.equal(computeAnnual(c).bonus,0);c.answers.children.push(structuredClone(c.answers.children[0]));assert(computeAnnual(c).questions.some(q=>q.key==='children'));c.year=2026;assert(computeAnnual(c).questions.some(q=>q.key==='year'));});
test('KH threshold is gross per document, including mixed VAT rows',()=>{const c=fixture('monthly'),d=invoice({date:'2026-05-10',base:800000,direction:'expense'});d.fields.rows.push({rate:12,baseCents:100000,vatCents:12000});d.fields.totalCents=1080000;c.documents.push(d);const r=computeMonthly(c);assert.equal(r.status,'READY_FOR_EXPORT');assert.equal(r.rows[0].section,'B2');assert.equal(r.inputTax,1800);assert(monthlyForms(c,r,'2026-06-15')[0].xml.includes('zakl_dane2="1000.00"'));});
test('exactly 10000 CZK is aggregate, over 10000 is individual; unclaimed expense excluded with reason',()=>{const c=fixture('monthly'),d=invoice({date:'2026-05-10',base:826446,direction:'expense'});d.fields.rows[0].vatCents=173554;d.fields.totalCents=1000000;c.documents.push(d);assert.equal(computeMonthly(c).rows[0].section,'B3');d.fields.claimVat=false;assert(computeMonthly(c).questions.some(q=>q.key==='document.invoice'));d.fields.vatDecisionReason='Soukromý nákup';assert.equal(computeMonthly(c).rows.length,0);});
test('inconsistent document sums, future receipt date and mixed currencies block monthly export',()=>{const c=fixture('monthly'),d=invoice({date:'2026-05-10',direction:'expense'});c.documents.push(d);d.fields.totalCents++;assert(validateDocument(d).length);d.fields.totalCents--;d.fields.receivedDate='2026-06-01';assert(computeMonthly(c).questions.some(q=>q.key==='document.invoice'));d.fields.currency='EUR';assert.throws(()=>monthlyForms(c,computeMonthly(c),'2026-06-15'));});
test('reimported business identity from another scan is detected as duplicate',()=>{const c=fixture(),d=invoice();c.documents.push(d,{...structuredClone(d),id:'another-source'});assert(computeAnnual(c).questions.some(q=>q.key==='duplicate.another-source'));});
test('early electronic filing still uses basic insurance deadline; real filing moves payment deadline',()=>{const c=fixture();c.answers.filingMode='electronic';assert.equal(deadlines(c,'2026-03-01').find(d=>d.id==='cssz').due,'2026-06-04');c.filings={dpfo:{date:'2026-03-29'},cssz:{date:'2026-03-29'}};assert.equal(deadlines(c,'2026-03-30').find(d=>d.id==='cssz').due,'2026-05-04');assert.equal(deadlines(c,'2026-03-30').find(d=>d.id==='csszPayment').due,'2026-04-07');assert.equal(businessDate('2026-04-03'),'2026-04-07');});
test('unknown filing method keeps alternative deadlines conditional, calendar has only confirmed due dates',()=>{const c=fixture();delete c.answers.filingMode;const rows=deadlines(c,'2026-04-02');assert(rows.every(x=>x.status==='CONDITIONAL'));assert(!calendar(c,rows,'2026-01-01T00:00:00.000Z').includes('BEGIN:VEVENT'));});
test('PDF invoice extraction carries source evidence and never approves the document',()=>{const p={page:1,method:'pdf-text',text:'Faktura 2025-01\nDIČ CZ7001010007 DIČ CZ12345679\nDatum vystavení 05.01.2025\nDatum zdan. plnění 05.01.2025\nCelkem bez DPH 10 000,00 Kč\nDPH 21 % 2 100,00 Kč\n12 100,00 KčCena'};const d=extractDocument(p,{id:'source'},fixture().profile);assert.equal(d.status,'draft');assert.equal(d.fields.direction,'income');assert.equal(d.fields.totalCents,1210000);assert.equal(d.provenance.rows.sourceId,'source');});
test('XML serialization escapes user identity and refuses unready annual state',()=>{const c=fixture();c.profile.lastName='Test & <Příklad>';c.documents.push(invoice());const r=computeAnnual(c);assert(annualForms(c,r,'2026-03-29')[0].xml.includes('Test &amp; &lt;Příklad&gt;'));r.status='NEEDS_REVIEW';assert.throws(()=>annualForms(c,r,'2026-03-29'));});
test('mortgage limit follows paid months and requires household allocation',()=>{const c=fixture();c.documents.push(invoice({base:500000000}));Object.assign(c.answers,{mortgage:true,mortgageAmount:10000000,mortgageEligible:true,mortgageEvidence:'support',housingNeedAcquired:'from2021',mortgageMonths:3,mortgageHouseholdAllocationConfirmed:true});assert.equal(computeAnnual(c).claimed.mortgage,37500);delete c.answers.mortgageMonths;assert(computeAnnual(c).questions.some(q=>q.key==='mortgageMonths'));});
test('cent calculations remain exact; incompatible whole-crown form projection is blocked',()=>{const c=fixture();c.documents.push(invoice({base:10001}));const r=computeAnnual(c);assert.equal(r.income,100.01);assert.equal(r.expenses,60.01);assert.equal(r.base,40);c.documents[1]=invoice({base:24998});assert(computeAnnual(c).questions.some(q=>q.key==='roundingReview'));c.documents[1]=invoice({base:150000003});const projected=computeAnnual(c);assert.equal(projected.base,600000.01);assert.equal(projected.insuranceTaxBase,600000);assert.equal(projected.health,40500);assert.equal(projected.social,96360);});
test('OZP serialized row 43 uses advances minus insurance, with selected filing and advance type',()=>{const c=fixture();c.documents.push(invoice());const r=computeAnnual(c),fields=ozpPDFFields(c,r,'2026-09-12');assert.equal(fields.radek_43,-r.healthBalance);assert.equal(fields.rodne_cislo_1,undefined);assert.equal(fields.rodne_cislo_2,undefined);assert.equal(fields.box_typ,1);assert.equal(fields.box_priznani_k_dani,1);assert.equal(fields.box_radek_51,1);assert(annualForms(c,r,'2026-09-12')[2].xml.includes('<klicRadku>43</klicRadku><hodnotaRadku>-37712</hodnotaRadku>'));});
test('2026 social advances use July change, direct monthly basis and current maximum',()=>{assert.equal(socialAdvance2026(4000,'2026-06-01').amount,5720);assert.equal(socialAdvance2026(4000,'2026-07-01').amount,5005);assert.equal(socialAdvance2026(1000000,'2026-07-01').amount,13384);assert.equal(socialAdvance2026(10000000,'2026-07-01').amount,57194);});
test('actual overview dates control recurring premiums; income tax advance is not applied before new obligation',()=>{const c=fixture();c.documents.push(invoice({base:220000000}));c.filings={dpfo:{date:'2026-03-29'},cssz:{date:'2026-03-29'},health:{date:'2026-03-29'}};const rows=deadlines(c,'2026-03-30');assert.equal(rows.find(x=>x.id==='csszAdvance-2026-04').amount,13384);assert(rows.some(x=>x.id==='healthAdvance-2026-03'));assert(!rows.some(x=>x.id==='csszAdvance-2026-03'));assert(!rows.some(x=>x.id==='taxAdvance-2026-3'));assert.equal(rows.find(x=>x.id==='taxAdvance-2026-6').amount,47700);});
test('a document for a different taxpayer and an undecided refund cannot be silently exported',()=>{const c=fixture();c.documents.push(invoice());c.documents[1].fields.supplierDic='CZ11111111';assert(computeAnnual(c).questions.some(q=>q.key==='document.invoice'));c.documents[1].fields.supplierDic='CZ7001010007';c.answers.healthAdvances=10000000;assert(computeAnnual(c).questions.some(q=>q.key==='refundDisposition'));});
summary();
