import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { WorkspaceFiles, flattenTree } = require('../intentsmith-ide/extensions/intentsmith-studio2/lib/browser/workspace-files.js');
const tree = [{ n: 'src', d: true, children: [{ n: 'main.js', d: false }, { n: '..', d: false }] }];
assert.deepEqual(flattenTree(tree).map(item => item.path), ['src','src/main.js']);
const session = { id: 's1', _projectId: 5 };
let saved = false;
let conflict = true;
const calls = [];
const files = new WorkspaceFiles({ backendUrl: () => 'http://127.0.0.1:1234', fetchImpl: async (url, options) => {
  calls.push({ url, method: options.method || 'GET' });
  if (url.includes('/tree?')) return { ok: true, json: async () => ({ root: '/tmp/project', tree }) };
  if (url.includes('/ls?')) return { ok: true, json: async () => ({ entries: [{ name: 'main.js', isDir: false }] }) };
  if (options.method === 'POST') {
    assert.equal(JSON.parse(options.body).expectedHash, 'old-hash');
    if (conflict) return { ok: false, status: 409, json: async () => ({ error: 'changed' }) };
    saved = true;
    return { ok: true, json: async () => ({ ok: true, path: 'src/main.js' }) };
  }
  return { ok: true, json: async () => ({ path: 'src/main.js', content: saved ? 'new' : 'old', hash: saved ? 'new-hash' : 'old-hash' }) };
} });
assert.equal(await files.loadTree(session), true);
assert.equal(await files.open(session, '../escape'), false);
assert.equal(await files.open(session, 'src/main.js'), true);
assert.equal(await files.completePath(session, 'cat src/ma'), 'cat src/main.js');
assert.equal(await files.completePath(session, 'cat ../secret'), null);
assert.equal(calls.filter(call => call.url.includes('/ls?')).length, 1);
files.edit(session, 'new');
assert.equal(files.anyDirty(), true);
assert.equal(await files.save(session), false);
assert.equal(files.entry(session).editor.draft, 'new');
assert.equal(files.entry(session).editor.dirty, true);
assert.match(files.entry(session).error, /jiný proces/);
assert.equal(files.entry(session).saveUncertain, true);
assert.equal(await files.save(session), false);
assert.equal(calls.filter(call => call.method === 'POST').length, 1);
assert.equal(await files.verifySave(session), false);
assert.equal(files.entry(session).saveUncertain, false);
conflict = false;
assert.equal(await files.save(session), true);
assert.equal(files.anyDirty(), false);
assert.deepEqual(session._modifiedFiles, ['src/main.js']);
assert.deepEqual(session._openedFiles, ['src/main.js']);
session._projectId = 6;
assert.equal(await files.completePath(session, 'cat src/ma'), null);
assert.equal(await files.open(session, 'src/main.js'), false);
assert.equal(files.entry(session).projectId, '5');
assert.equal(calls.filter(call => call.method === 'POST').length, 2);
let readbackFails = true;
let writes = 0;
let disk = 'old';
const uncertain = new WorkspaceFiles({ backendUrl: () => 'http://127.0.0.1:1234', fetchImpl: async (url, options) => {
  if (url.includes('/tree?')) return { ok: true, json: async () => ({ root: '/tmp/second', tree }) };
  if (options.method === 'POST') { writes++; disk = JSON.parse(options.body).content;
    return { ok: true, json: async () => ({ ok: true, path: 'src/main.js' }) }; }
  if (readbackFails && disk === 'new') { readbackFails = false; throw new Error('readback unavailable'); }
  return { ok: true, json: async () => ({ path: 'src/main.js', content: disk, hash: disk + '-hash' }) };
} });
const another = { id: 's2', _projectId: 6, _modifiedFiles: [], _fileChanges: {}, _openedFiles: [] };
assert.equal(await uncertain.loadTree(another), true);
assert.equal(await uncertain.open(another, 'src/main.js'), true);
uncertain.edit(another, 'new');
assert.equal(await uncertain.save(another), false);
assert.equal(uncertain.entry(another).saveUncertain, true);
assert.equal(another._modifiedFiles.length, 0);
assert.equal(await uncertain.save(another), false);
assert.equal(writes, 1);
assert.equal(await uncertain.verifySave(another), true);
assert.equal(uncertain.entry(another).saveUncertain, false);
assert.equal(uncertain.entry(another).editor.dirty, false);
assert.deepEqual(another._modifiedFiles, ['src/main.js']);
assert.equal(writes, 1);
let releasePost;
const postGate = new Promise(resolve => { releasePost = resolve; });
let racingDisk = 'before';
let posts = 0;
const racing = new WorkspaceFiles({ backendUrl: () => 'http://127.0.0.1:1234', fetchImpl: async (url, options) => {
  if (url.includes('/tree?')) return { ok: true, json: async () => ({ root: '/tmp/racing', tree }) };
  if (options.method === 'POST') {
    posts++;
    const sent = JSON.parse(options.body).content;
    if (posts === 1) await postGate;
    racingDisk = sent;
    return { ok: true, json: async () => ({ ok: true, path: 'src/main.js' }) };
  }
  return { ok: true, json: async () => ({ path: 'src/main.js', content: racingDisk, hash: racingDisk + '-hash' }) };
} });
const racingSession = { id: 's3', _projectId: 7, _modifiedFiles: [], _fileChanges: {}, _openedFiles: [] };
assert.equal(await racing.loadTree(racingSession), true);
assert.equal(await racing.open(racingSession, 'src/main.js'), true);
racing.edit(racingSession, 'first');
const inFlight = racing.save(racingSession);
racing.edit(racingSession, 'second');
racing.discard(racingSession);
assert.equal(racing.entry(racingSession).editor.draft, 'second');
releasePost();
assert.equal(await inFlight, true);
assert.equal(racing.entry(racingSession).editor.original, 'first');
assert.equal(racing.entry(racingSession).editor.draft, 'second');
assert.equal(racing.entry(racingSession).editor.dirty, true);
assert.equal(await racing.save(racingSession), true);
assert.equal(racingDisk, 'second');
assert.equal(racing.entry(racingSession).editor.dirty, false);
console.log('PASS scoped tree/completion, 409 guard, uncertain write recovery, and in-flight edit preservation');
