/**
 * @c3/design-viewer — Protocol (common)
 *
 * Design Viewer reads EXCLUSIVELY from files, NEVER from chat.
 *
 * Data sources:
 *   - design/architecture.md — generated by C3
 *   - design/sprints.md — sprint plan
 *   - project.json → context — metadata (stack, decisions)
 *
 * Chat is INPUT (user says what they want).
 * Design Viewer is OUTPUT (what C3 designed).
 * Mixing them breaks the "design ≠ conversation" concept.
 *
 * Immutability Guard:
 *   design/*.md files are READ-ONLY in the editor.
 *   Edit only via chat → C3 regenerates file.
 *   Explicit unlock via command with warning dialog.
 */

export const C3DesignViewerPath = '/services/c3-design-viewer';
export const C3DesignViewer = Symbol('C3DesignViewer');

// ─── Design Document Model ───────────────────────────────

export interface DesignDocument {
  /** Raw architecture markdown */
  architecture: string | null;
  /** Raw sprints markdown */
  sprints: string | null;
  /** Project metadata from project.json.context */
  metadata: DesignMetadata | null;
  /** Parsed outline sections */
  outline: OutlineSection[];
  /** Timestamp of last modification */
  lastModified: string;
}

export interface DesignMetadata {
  stack: Record<string, string>;
  decisions: DesignDecision[];
  currentSprint: number;
  totalSprints: number;
  designTurns: number;
  projectName: string;
  phase: string;
}

export interface DesignDecision {
  what: string;
  why: string;
  when: string;
}

export interface OutlineSection {
  id: string;
  title: string;
  level: number;  // 1=h1, 2=h2, etc.
  lineStart: number;
  lineEnd: number;
  source: 'architecture' | 'sprints';
  children: OutlineSection[];
}

// ─── Service Interface ───────────────────────────────────

export interface C3DesignViewer {
  /** Load design from project filesystem (never from chat) */
  loadDesign(projectPath: string): Promise<DesignDocument>;

  /** Watch for design file changes */
  watchDesign(projectPath: string): Promise<void>;

  /** Stop watching */
  unwatchDesign(): Promise<void>;

  /** Check if design files exist */
  hasDesign(projectPath: string): Promise<boolean>;
}

// ─── Events (backend → frontend) ─────────────────────────

export const C3DesignViewerClient = Symbol('C3DesignViewerClient');

export interface C3DesignViewerClient {
  /** Fired when a design file changes on disk */
  onDesignChanged(doc: DesignDocument): void;
}

// ─── Immutability Guard ──────────────────────────────────

/**
 * Pattern for design files that should be read-only.
 * FileSystemProvider uses this to mark them.
 */
export const DESIGN_FILE_PATTERN = /^design\/.*\.md$/;

/** Banner text shown when opening a design file */
export const DESIGN_READONLY_BANNER =
  'Tento soubor je generovaný C3. Upravte přes chat.';

/** Unlock command ID */
export const UNLOCK_DESIGN_COMMAND = 'c3.design.unlock';
